// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/ujds/record/v1/record.proto

package v1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/ashep/ujds/sdk/proto/ujds/record/v1"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// RecordServiceName is the fully-qualified name of the RecordService service.
	RecordServiceName = "ujds.record.v1.RecordService"
)

// RecordServiceClient is a client for the ujds.record.v1.RecordService service.
type RecordServiceClient interface {
	Push(context.Context, *connect_go.Request[v1.PushRequest]) (*connect_go.Response[v1.PushResponse], error)
	Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error)
	Find(context.Context, *connect_go.Request[v1.FindRequest]) (*connect_go.Response[v1.FindResponse], error)
	History(context.Context, *connect_go.Request[v1.HistoryRequest]) (*connect_go.Response[v1.HistoryResponse], error)
}

// NewRecordServiceClient constructs a client for the ujds.record.v1.RecordService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRecordServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) RecordServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &recordServiceClient{
		push: connect_go.NewClient[v1.PushRequest, v1.PushResponse](
			httpClient,
			baseURL+"/ujds.record.v1.RecordService/Push",
			opts...,
		),
		get: connect_go.NewClient[v1.GetRequest, v1.GetResponse](
			httpClient,
			baseURL+"/ujds.record.v1.RecordService/Get",
			opts...,
		),
		find: connect_go.NewClient[v1.FindRequest, v1.FindResponse](
			httpClient,
			baseURL+"/ujds.record.v1.RecordService/Find",
			opts...,
		),
		history: connect_go.NewClient[v1.HistoryRequest, v1.HistoryResponse](
			httpClient,
			baseURL+"/ujds.record.v1.RecordService/History",
			opts...,
		),
	}
}

// recordServiceClient implements RecordServiceClient.
type recordServiceClient struct {
	push    *connect_go.Client[v1.PushRequest, v1.PushResponse]
	get     *connect_go.Client[v1.GetRequest, v1.GetResponse]
	find    *connect_go.Client[v1.FindRequest, v1.FindResponse]
	history *connect_go.Client[v1.HistoryRequest, v1.HistoryResponse]
}

// Push calls ujds.record.v1.RecordService.Push.
func (c *recordServiceClient) Push(ctx context.Context, req *connect_go.Request[v1.PushRequest]) (*connect_go.Response[v1.PushResponse], error) {
	return c.push.CallUnary(ctx, req)
}

// Get calls ujds.record.v1.RecordService.Get.
func (c *recordServiceClient) Get(ctx context.Context, req *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Find calls ujds.record.v1.RecordService.Find.
func (c *recordServiceClient) Find(ctx context.Context, req *connect_go.Request[v1.FindRequest]) (*connect_go.Response[v1.FindResponse], error) {
	return c.find.CallUnary(ctx, req)
}

// History calls ujds.record.v1.RecordService.History.
func (c *recordServiceClient) History(ctx context.Context, req *connect_go.Request[v1.HistoryRequest]) (*connect_go.Response[v1.HistoryResponse], error) {
	return c.history.CallUnary(ctx, req)
}

// RecordServiceHandler is an implementation of the ujds.record.v1.RecordService service.
type RecordServiceHandler interface {
	Push(context.Context, *connect_go.Request[v1.PushRequest]) (*connect_go.Response[v1.PushResponse], error)
	Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error)
	Find(context.Context, *connect_go.Request[v1.FindRequest]) (*connect_go.Response[v1.FindResponse], error)
	History(context.Context, *connect_go.Request[v1.HistoryRequest]) (*connect_go.Response[v1.HistoryResponse], error)
}

// NewRecordServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRecordServiceHandler(svc RecordServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/ujds.record.v1.RecordService/Push", connect_go.NewUnaryHandler(
		"/ujds.record.v1.RecordService/Push",
		svc.Push,
		opts...,
	))
	mux.Handle("/ujds.record.v1.RecordService/Get", connect_go.NewUnaryHandler(
		"/ujds.record.v1.RecordService/Get",
		svc.Get,
		opts...,
	))
	mux.Handle("/ujds.record.v1.RecordService/Find", connect_go.NewUnaryHandler(
		"/ujds.record.v1.RecordService/Find",
		svc.Find,
		opts...,
	))
	mux.Handle("/ujds.record.v1.RecordService/History", connect_go.NewUnaryHandler(
		"/ujds.record.v1.RecordService/History",
		svc.History,
		opts...,
	))
	return "/ujds.record.v1.RecordService/", mux
}

// UnimplementedRecordServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRecordServiceHandler struct{}

func (UnimplementedRecordServiceHandler) Push(context.Context, *connect_go.Request[v1.PushRequest]) (*connect_go.Response[v1.PushResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ujds.record.v1.RecordService.Push is not implemented"))
}

func (UnimplementedRecordServiceHandler) Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.GetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ujds.record.v1.RecordService.Get is not implemented"))
}

func (UnimplementedRecordServiceHandler) Find(context.Context, *connect_go.Request[v1.FindRequest]) (*connect_go.Response[v1.FindResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ujds.record.v1.RecordService.Find is not implemented"))
}

func (UnimplementedRecordServiceHandler) History(context.Context, *connect_go.Request[v1.HistoryRequest]) (*connect_go.Response[v1.HistoryResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ujds.record.v1.RecordService.History is not implemented"))
}
